strain_mapping:
  004_S2_contig_1_C_pilon: Varoivorax
  004_S2_contig_3_C_pilon: Varoivorax
  005_S3_contig_2_C_pilon: Flavobacterium2
  012_S5_contig_2_C_pilon: Flavobacterium
  015_S7_contig_1_C_pilon: Mucilaginibacter
  018_S8_contig_2_C_pilon: Curtobacterium
  018_S8_contig_3_C_pilon: Curtobacterium
  PB01_ctg.s1.000000F: Cellulomonas
  PB02_ctg.s1.000000F: Bradyrhizobium
  PB03_ctg.s1.000000F: Luteibacter
  PB04_ctg.s1.000000F: Phenlyobacterium
  PB05_ctg.s1.000000F: Mesorhizobium
  PB05_ctg.s2.168: Mesorhizobium
  PB06_ctg.s1.0: Lysobacter
  PB07_ctg.s1.000000F: Caulobacter
  PB07_ctg.s1.1: Caulobacter
  PB08_ctg.s1.000000F: Pseudomonas1
  PB09_ctg.s1.000000F: Devosia
  PB10_ctg.s1.000000F: Cohnella
  PB11_ctg.s1.000000F: Tardiphaga
  PB11_ctg.s1.000000F;PB11_ctg.s1.000000F: Tardiphaga
  PB12_ctg.s1.000000F: Rahnella
  PB12_ctg.s1.1: Rahnella
  PB12_ctg.s2.000014F: Rahnella
  PB13_ctg.s1.000000F: Rhodococcus
  PB13_ctg.s2.000005F: Rhodococcus
  PB14_ctg.s1.000000F: Pseudomonas2
  PB14_ctg.s2.000000F: Pseudomonas2
  PB14_ctg.s2.000009F: Pseudomonas2
  PB15_ctg.s1.000000F: Burkholderia
  PB15_ctg.s1.1: Burkholderia
  PB16_ctg.s1.000000F: Chitinophaga
